import Head from 'next/head'
import Main from '../components/Main'
import About from '../components/About'
import Services from '../components/Services'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Mahmud | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Services/>
      <Projects/>
      <Contact/>
    </div>
  )
}
